extern void readin(char* buffer, int clrdone);
extern void writeout(int sector, int drive);
extern void xor_cycle(char* buffer);
extern void puts32(char* str, int fg, int bg);
extern void setup_copy(int sectors);
extern void save_buffer(char* buffer, int drive);
extern void send(char* buffer, int IP, int port, int timeout);
extern void serve(int port);
extern void serve_await_connection(int timeout);
extern void serve_write(char* buffer);
extern void serve_read();
extern void serve_connection_close();
extern void sleep(int ms);
extern void render(char* buffer);
extern void play_sound(char* buffer, int size);
extern int checkpass();
extern int strcmp(char* buf1, char* buf2);
extern int strlen(char* str);
extern int getdrive();
extern void* FILE;
extern void* TEMPBUF;
extern void* NETBUF;
extern void* PROMPTBUF;
extern void* PASSBUF;
extern void* SHUTDOWN_SOUND;
