extern void readin(char* buffer, short short int clrdone, short short int blind);
extern void writeout(long int sector, short short int drive);
extern void xor_cycle(char* buffer);
extern void puts32(char* str, short short int fg, short short int bg);
extern void setup_copy(int sectors, short short int drive);
extern void save_buffer(char* buffer, short short int drive);
extern void render(char* buffer);
extern void screen_fill(long int col);
extern void render_buf(void* img_buf);
extern void save_graphics_buf();
extern void wait_for_key();
extern int checkpass();
extern int strcmp(char* buf1, char* buf2);
extern int strlen(char* str);
extern int getdrive();
extern int malloc(long int size);
extern void free(long int size);
extern char* itoa(long int num, short short int capitalized, char* location);
extern int ASLR_generate_address();
extern void lexec_core(long int address);
extern int sectorize(long int number);
extern void sleep(long int seconds);
extern void* TEMPBUF;
extern void* PROMPTBUF;
extern void* PASSBUF;
extern void* renderbuf_loc;
extern void* sleep_loc;
